@startuml overview

title Tomato主要调用流程


autonumber

IInvokeCaller -> IRpcClient : AsyncCall(Message)
IRpcClient -> IServiceRouter : GetServiceRouter(Message)
IRpcClient <-- IServiceRouter : IRouter

alt IRouter.RouterMode == "Remote"
    IRpcClient -> IRpcClient : SendAsync(EndPoint,Message)
else IRouter.RouterMode == "Local"
    IRpcClient -> IServiceActorLocator : GetServiceActor(Message)
    IRpcClient <-- IServiceActorLocator : IServiceActor
    IRpcClient -> IServiceActor : ReceiveAsync(ISocketContext,Message)
end

@enduml

